FROM httpd:2.4


RUN apt-get update && apt-get install -y iputils-ping libapache2-mod-php

RUN mkdir -p /var/log/apache2 && chown -R www-data:www-data /var/log/apache2

RUN sed -i '/mod_unixd.so/s/^#//g' /usr/local/apache2/conf/httpd.conf
COPY apache/default.conf /usr/local/apache2/conf/httpd.conf

# Tạo thư mục log nếu chưa có
RUN mkdir -p /var/log/apache2

# Cấp quyền cho Apache để ghi vào thư mục log
RUN chown -R www-data:www-data /var/log/apache2

COPY src/ /var/www/html/

EXPOSE 80

CMD ["httpd-foreground"]