FROM httpd:2.4

RUN mkdir -p /var/log/apache2 && chown -R www-data:www-data /var/log/apache2
COPY apache/default.conf /usr/local/apache2/conf/httpd.conf

COPY src/ /usr/local/apache2/htdocs/

EXPOSE 80

CMD ["httpd-foreground"]